# Generated by Django 5.2.1 on 2025-09-04 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shift name (e.g., Morning, Afternoon, Night)",
                        max_length=100,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="locations.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["start_time"],
                "unique_together": {("camp", "name")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Team name", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="locations.camp",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Team members",
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_leader",
                    models.ForeignKey(
                        help_text="Team leader (must be a Manager or Admin)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["name"],
                "unique_together": {("camp", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("cleaner", "Cleaner"),
                            ("authority", "Authority"),
                        ],
                        help_text="User role",
                        max_length=20,
                    ),
                ),
                (
                    "is_team_leader",
                    models.BooleanField(
                        default=False, help_text="Is this user a team leader?"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is user active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned camp",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.camp",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="CompoundAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_compounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="locations.compound",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compound_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compound Assignment",
                "verbose_name_plural": "Compound Assignments",
                "ordering": ["-assigned_at"],
                "unique_together": {("user", "compound")},
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Route priority (higher number = higher priority)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="locations.compound",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="accounts.shift",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["-priority", "team__name"],
                "unique_together": {("team", "shift", "compound")},
            },
        ),
    ]
