# Generated by Django 4.2.23 on 2025-09-05 00:49

from django.db import migrations, models
import uuid


def add_uuid_field(apps, schema_editor):
    """Add UUID field to existing UserProfile records."""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        profile.uuid = uuid.uuid4()
        profile.save(update_fields=['uuid'])


def reverse_add_uuid(apps, schema_editor):
    """This migration cannot be reversed safely."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            add_uuid_field,
            reverse_add_uuid,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
