# Generated by Django 4.2.23 on 2025-09-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_alter_camp_month_cutoff_day_alter_camp_timezone"),
        ("accounts", "0002_auto_20250905_0249"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("team", "shift")},
        ),
        migrations.AddField(
            model_name="route",
            name="compounds",
            field=models.ManyToManyField(
                help_text="Compounds assigned to this route",
                related_name="routes",
                to="locations.compound",
            ),
        ),
        migrations.RemoveField(
            model_name="route",
            name="compound",
        ),
    ]
