# Generated by Django 4.2.23 on 2025-09-05 02:34

from django.db import migrations


def migrate_route_compounds(apps, schema_editor):
    """
    Migrate existing routes to use the new compounds ManyToManyField.
    This is a no-op since we're handling the migration in the model change.
    """
    pass


def reverse_migrate_route_compounds(apps, schema_editor):
    """
    Reverse migration - no-op since we can't easily reverse this.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_route_unique_together_route_compounds_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_route_compounds, reverse_migrate_route_compounds),
    ]
