# Generated by Django 4.2.23 on 2025-09-05 02:37

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_migrate_route_compounds"),
    ]

    operations = [
        # NOTE: The `accounts_route_compounds` table is already created by the
        # ManyToManyField added in 0003. Registering the explicit RouteCompounds
        # model here must therefore be a STATE-ONLY operation so we don't try to
        # re-create (or later drop) the shared M2M through table on a fresh DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='RouteCompounds',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('route', models.ForeignKey(on_delete=models.deletion.CASCADE, to='accounts.route')),
                        ('compound', models.ForeignKey(on_delete=models.deletion.CASCADE, to='locations.compound')),
                    ],
                    options={
                        'db_table': 'accounts_route_compounds',
                    },
                ),
                migrations.AddConstraint(
                    model_name='routecompounds',
                    constraint=models.UniqueConstraint(fields=('route', 'compound'), name='unique_route_compound'),
                ),
            ],
            database_operations=[],
        ),
    ]
