# Generated by Django 4.2.23 on 2025-09-05 17:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0002_alter_camp_month_cutoff_day_alter_camp_timezone"),
        ("accounts", "0006_remove_compound_id_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCleaningTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_date",
                    models.DateField(help_text="Date for this cleaning task"),
                ),
                (
                    "index_in_day",
                    models.IntegerField(
                        default=1,
                        help_text="Index of this task within the day (1, 2, 3, etc.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("requested", "Requested"),
                            ("urgent", "Urgent"),
                        ],
                        default="regular",
                        help_text="Type of cleaning task",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("missed", "Missed"),
                            ("re_clean_required", "Re-clean Required"),
                        ],
                        default="planned",
                        help_text="Current state of the task",
                        max_length=20,
                    ),
                ),
                (
                    "sla_credit_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="SLA credit earned for completing this task (in sqm)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False, help_text="Is this an urgent task?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "assigned_to_team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="accounts.team",
                    ),
                ),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this task (if individual assignment)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_tasks",
                        to="locations.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Cleaning Task",
                "verbose_name_plural": "Daily Cleaning Tasks",
                "ordering": ["task_date", "index_in_day", "room__room_code"],
                "unique_together": {("room", "task_date", "index_in_day")},
            },
        ),
        # State-only: RouteCompounds is a phantom model mapped to the shared
        # `accounts_route_compounds` M2M through table (created in 0003). Only
        # remove it from migration state; never drop the underlying table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="RouteCompounds",
                ),
            ],
            database_operations=[],
        ),
    ]
