# Generated by Django 4.2.23 on 2025-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_dailycleaningtask_delete_routecompounds"),
        ("locations", "0002_alter_camp_month_cutoff_day_alter_camp_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteCompounds",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("route", models.ForeignKey(on_delete=models.CASCADE, to="accounts.route")),
                ("compound", models.ForeignKey(on_delete=models.CASCADE, to="locations.compound")),
            ],
            options={
                "db_table": "accounts_route_compounds",
            },
        ),
        migrations.AddConstraint(
            model_name="routecompounds",
            constraint=models.UniqueConstraint(fields=("route", "compound"), name="unique_route_compound"),
        ),
    ]
