# Generated by Django 4.2.23 on 2025-09-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_create_route_compounds_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycleaningtask",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Shift assigned to this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_tasks",
                to="accounts.shift",
            ),
        ),
        # State-only removal of the phantom RouteCompounds model (see 0007/0008).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="RouteCompounds",
                ),
            ],
            database_operations=[],
        ),
    ]
