# Generated by Django 4.2.23 on 2025-09-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_dailycleaningtask_shift_delete_routecompounds"),
    ]

    operations = [
        # Add shift field to Team
        migrations.AddField(
            model_name="team",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Shift when this team works",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="accounts.shift",
            ),
        ),
    ]