# Generated by Django 4.2.23 on 2025-09-06 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_auto_20250906_0143"),
    ]

    operations = [
        # Update unique constraint for Route
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("team",)},
        ),
    ]