# Generated by Django 4.2.23 on 2025-09-06 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_auto_20250906_0143"),
    ]

    operations = [
        # Skip the problematic migration and just set the unique constraint
        migrations.RunSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS accounts_route_team_unique ON accounts_route(team_id) WHERE is_active = 1;",
            reverse_sql="DROP INDEX IF EXISTS accounts_route_team_unique;"
        ),
    ]
