# Generated by Django 4.2.23 on 2025-09-06 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_auto_20250906_0144"),
        ("accounts", "0012_auto_20250906_0219"),
    ]

    operations = []
