# Generated by Django 4.2.23 on 2025-09-06 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_merge_0011_auto_20250906_0144_0012_auto_20250906_0219"),
    ]

    operations = [
        # Remove the shift_id column from accounts_route table
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS accounts_route_shift_id_22ee4c5d;
            ALTER TABLE accounts_route DROP COLUMN shift_id;
            """,
            reverse_sql="ALTER TABLE accounts_route ADD COLUMN shift_id INTEGER REFERENCES accounts_shift(id);"
        ),
    ]
