# Generated by Django 4.2.23 on 2025-09-06 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_auto_20250906_0223"),
    ]

    operations = [
        # Remove the unique constraint on team_id to allow multiple routes per team
        migrations.RunSQL(
            "DROP INDEX IF EXISTS accounts_route_team_unique;",
            reverse_sql="CREATE UNIQUE INDEX accounts_route_team_unique ON accounts_route(team_id) WHERE is_active = 1;"
        ),
    ]
