# Generated by Django 4.2.24 on 2025-09-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20250906_0225'),
    ]

    operations = [
        # The `shift_id` column was already dropped from the database by the raw
        # SQL in 0014 (a DB-only operation). Here we only reconcile the migration
        # state so we don't try to drop the column a second time.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='route',
                    name='shift',
                ),
            ],
            database_operations=[],
        ),
    ]
