# Generated by Django 4.2.24 on 2025-09-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20250906_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='shift',
        ),
    ]
