# Generated by Django 4.2.24 on 2026-07-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_route_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('cleaning', 'Cleaning Team'), ('collection', 'Garbage Collection Team')], default='cleaning', help_text='Type of team (Cleaning or Garbage Collection)', max_length=50),
        ),
    ]
