# Generated by Django 4.2.30 on 2026-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_team_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operations_manager', 'Operations Manager'), ('cleaner', 'Cleaner'), ('authority', 'Authority')], help_text='User role', max_length=20),
        ),
    ]
