# Generated by Django 4.2.30 on 2026-07-07 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_building_options_alter_camp_options_and_more'),
        ('accounts', '0018_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['team__name', 'weekday'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, help_text='Optional route label', max_length=120),
        ),
        migrations.AddField(
            model_name='route',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Weekday this route runs (0=Mon..6=Sun)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='compounds',
            field=models.ManyToManyField(blank=True, help_text='Zones assigned to this route (derived from streets)', related_name='routes', to='locations.compound'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Field Manager'), ('operations_manager', 'Operations Manager'), ('cleaner', 'Cleaner'), ('authority', 'Authority')], help_text='User role', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('team', 'weekday')},
        ),
        migrations.CreateModel(
            name='RouteStreet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, help_text='Order of this street within the route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_memberships', to='locations.building')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_streets', to='accounts.route')),
            ],
            options={
                'verbose_name': 'Route Street',
                'verbose_name_plural': 'Route Streets',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'building')},
            },
        ),
        migrations.CreateModel(
            name='PlanGenerationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadence', models.CharField(choices=[('weekly', 'Every week'), ('biweekly', 'Every second week')], default='weekly', max_length=20)),
                ('anchor_date', models.DateField(default=django.utils.timezone.localdate, help_text='Reference Monday used to compute bi-weekly parity')),
                ('last_generated_on', models.DateField(blank=True, help_text='Last date tasks were generated', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_config', to='locations.camp')),
            ],
            options={
                'verbose_name': 'Plan Generation Config',
                'verbose_name_plural': 'Plan Generation Configs',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='streets',
            field=models.ManyToManyField(blank=True, help_text='Streets serviced on this route', related_name='routes', through='accounts.RouteStreet', to='locations.building'),
        ),
    ]
