# Generated by Django 4.2.30 on 2026-07-07 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_alter_route_options_alter_route_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='employee_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of employees on this team (including the leader)'),
        ),
        migrations.AddField(
            model_name='team',
            name='equipment',
            field=models.TextField(blank=True, help_text='Equipment assigned to this team'),
        ),
        migrations.AddField(
            model_name='team',
            name='vehicle',
            field=models.CharField(blank=True, help_text='Vehicle assigned to this team (e.g. Truck GJ-123-AB)', max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Team members (optional)', related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(help_text='Team leader', on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
