# Generated by Django 4.2.23 on 2025-09-02 15:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Report template name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Report description"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_cleaning", "Daily Cleaning Report"),
                            ("weekly_summary", "Weekly Summary Report"),
                            ("monthly_sla", "Monthly SLA Report"),
                            ("roster_status", "Roster Status Report"),
                            ("audit_summary", "Audit Summary Report"),
                            ("custom", "Custom Report"),
                        ],
                        help_text="Type of report",
                        max_length=50,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Report parameters and filters"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Can other users use this template"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.ForeignKey(
                        blank=True,
                        help_text="Camp this template is for (null for global templates)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.camp",
                    ),
                ),
                (
                    "compound",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compound this template is for (null for camp-wide templates)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.compound",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Scheduled report name", max_length=200),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        help_text="How often to run the report",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of week (0=Monday, 6=Sunday) for weekly reports",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month for monthly reports",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        default=datetime.time(15, 53, 55, 112270),
                        help_text="Time of day to run the report",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses to send reports to",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_reports",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Report",
                "verbose_name_plural": "Scheduled Reports",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("record_count", models.IntegerField(blank=True, null=True)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the generated report file",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_traceback", models.TextField(blank=True, null=True)),
                (
                    "parameters_used",
                    models.JSONField(
                        default=dict, help_text="Parameters used for this execution"
                    ),
                ),
                (
                    "scheduled_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.scheduledreport",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Execution",
                "verbose_name_plural": "Report Executions",
                "ordering": ["-started_at"],
            },
        ),
    ]
