# Generated by Django 4.2.23 on 2025-09-05 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("method", models.CharField(help_text="HTTP method", max_length=10)),
                ("path", models.CharField(help_text="Request path", max_length=500)),
                ("status_code", models.IntegerField(help_text="HTTP status code")),
                (
                    "latency_ms",
                    models.IntegerField(help_text="Request latency in milliseconds"),
                ),
                (
                    "object_ref",
                    models.CharField(
                        blank=True,
                        help_text="Object reference (e.g., 'User:123')",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Action performed",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional details"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="audit_audit_status__b26560_idx"
                    ),
                ],
            },
        ),
    ]
