# Generated by Django 4.2.23 on 2025-09-02 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        help_text="Type of export (CSV, PDF, etc.)", max_length=50
                    ),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        help_text="Filters that were applied to the export"
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(help_text="Number of records exported"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported file",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Export",
                "verbose_name_plural": "Audit Log Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string from the request",
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="HTTP method (GET, POST, PUT, DELETE, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "path",
                    models.CharField(help_text="Request path/URL", max_length=500),
                ),
                (
                    "status_code",
                    models.IntegerField(help_text="HTTP status code of the response"),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Request latency in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed (e.g., 'login', 'scan_room', 'export_report')",
                        max_length=100,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of object affected (e.g., 'Room', 'ScanEvent', 'User')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the object affected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "object_ref",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable reference to the object",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        help_text="Request data (excluding sensitive information)",
                        null=True,
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        help_text="Response data (excluding sensitive information)",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the request failed",
                        null=True,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Django session key",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="audit_audit_ip_addr_4a1174_idx",
                    ),
                    models.Index(
                        fields=["method", "path"], name="audit_audit_method_d5eefe_idx"
                    ),
                    models.Index(
                        fields=["status_code", "timestamp"],
                        name="audit_audit_status__5c904b_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_audit_action_2a1328_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_audit_object__1f9df3_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                ],
            },
        ),
    ]
