# Generated by Django 4.2.23 on 2025-09-02 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UrgentCleaningRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for urgent cleaning request"),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        default="high",
                        help_text="Priority level of the urgent request",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("urgent_requested", "Urgent Requested"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="urgent_requested",
                        help_text="Current status of the urgent request",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_sent", models.BooleanField(default=False)),
                ("escalation_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cleaner assigned to this urgent request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_urgent_cleans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Contracting authority user who requested urgent cleaning",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_urgent_cleans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgent_requests",
                        to="locations.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Urgent Cleaning Request",
                "verbose_name_plural": "Urgent Cleaning Requests",
                "ordering": ["-priority_level", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "status"], name="authority_u_room_id_608bd8_idx"
                    ),
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="authority_u_request_b5fed6_idx",
                    ),
                    models.Index(
                        fields=["status", "priority_level"],
                        name="authority_u_status_99f7ce_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="authority_u_assigne_57c918_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecleanRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for re-clean request")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        help_text="Current status of the request",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Contracting authority user who requested re-clean",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_recleans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/Supervisor who resolved the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_recleans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclean_requests",
                        to="locations.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Re-clean Request",
                "verbose_name_plural": "Re-clean Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "status"], name="authority_r_room_id_d37233_idx"
                    ),
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="authority_r_request_13b6a6_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="authority_r_status_6de3f0_idx",
                    ),
                ],
            },
        ),
    ]
