# Generated by Django 4.2.23 on 2025-09-02 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Building code (e.g., BLDG-A)", max_length=50
                    ),
                ),
                ("name", models.CharField(help_text="Building name", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["compound", "code"],
            },
        ),
        migrations.CreateModel(
            name="Camp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Camp code (e.g., CAMP1)", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Camp name", max_length=200)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Camp timezone (e.g., 'Europe/Copenhagen')",
                        max_length=50,
                    ),
                ),
                (
                    "week_cutoff_day",
                    models.IntegerField(
                        default=4,
                        help_text="Week cut-off day (0=Monday, 6=Sunday)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "week_cutoff_hour",
                    models.IntegerField(
                        default=18,
                        help_text="Week cut-off hour (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "month_cutoff_day",
                    models.IntegerField(
                        default=25,
                        help_text="Month cut-off day (1-31)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "month_cutoff_hour",
                    models.IntegerField(
                        default=23,
                        help_text="Month cut-off hour (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "skip_holidays",
                    models.BooleanField(
                        default=True, help_text="Skip task generation on holidays"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Camp",
                "verbose_name_plural": "Camps",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Floor code (e.g., FL1)", max_length=50),
                ),
                ("name", models.CharField(help_text="Floor name", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="locations.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "ordering": ["building", "code"],
                "unique_together": {("building", "code")},
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shift name (e.g., Morning, Evening)", max_length=100
                    ),
                ),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="locations.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["camp", "start_time"],
                "unique_together": {("camp", "name")},
            },
        ),
        migrations.CreateModel(
            name="Compound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Compound code (e.g., DANISH)", max_length=50
                    ),
                ),
                ("name", models.CharField(help_text="Compound name", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compounds",
                        to="locations.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compound",
                "verbose_name_plural": "Compounds",
                "ordering": ["camp", "code"],
                "unique_together": {("camp", "code")},
            },
        ),
        migrations.AddField(
            model_name="building",
            name="compound",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="locations.compound",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Room code (e.g., RM101)", max_length=50
                    ),
                ),
                ("name", models.CharField(help_text="Room name", max_length=200)),
                (
                    "sqm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Room area in square meters",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is room active for cleaning"
                    ),
                ),
                (
                    "barcode_data",
                    models.CharField(
                        blank=True,
                        help_text="Generated barcode data for room identification",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "frequency_per_day",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of required cleans per day"
                    ),
                ),
                (
                    "frequency_per_week",
                    models.PositiveIntegerField(
                        default=7, help_text="Number of required cleans per week"
                    ),
                ),
                (
                    "time_window_start",
                    models.TimeField(
                        blank=True,
                        help_text="Preferred cleaning time window start",
                        null=True,
                    ),
                ),
                (
                    "time_window_end",
                    models.TimeField(
                        blank=True,
                        help_text="Preferred cleaning time window end",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="locations.floor",
                    ),
                ),
                (
                    "shift_binding",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required shift for this room (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["floor", "code"],
                "indexes": [
                    models.Index(
                        fields=["barcode_data"], name="locations_r_barcode_793aaf_idx"
                    )
                ],
                "unique_together": {("floor", "code")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="building",
            unique_together={("compound", "code")},
        ),
    ]
