# Generated by Django 5.2.1 on 2025-09-04 18:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique camp code", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Camp name", max_length=200)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="Camp timezone", max_length=50
                    ),
                ),
                (
                    "week_cutoff_day",
                    models.IntegerField(
                        default=6,
                        help_text="Week cutoff day (0=Monday, 6=Sunday)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "week_cutoff_hour",
                    models.IntegerField(
                        default=23,
                        help_text="Week cutoff hour (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "month_cutoff_day",
                    models.IntegerField(
                        default=31,
                        help_text="Month cutoff day",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "month_cutoff_hour",
                    models.IntegerField(
                        default=23,
                        help_text="Month cutoff hour (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "skip_holidays",
                    models.BooleanField(
                        default=True, help_text="Skip holidays in scheduling"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Camp",
                "verbose_name_plural": "Camps",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Compound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Compound code", max_length=50)),
                ("name", models.CharField(help_text="Compound name", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compounds",
                        to="locations.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compound",
                "verbose_name_plural": "Compounds",
                "ordering": ["name"],
                "unique_together": {("camp", "code")},
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Building code", max_length=50)),
                ("name", models.CharField(help_text="Building name", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="locations.compound",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["name"],
                "unique_together": {("compound", "code")},
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Floor code", max_length=50)),
                ("name", models.CharField(help_text="Floor name", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="locations.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "ordering": ["name"],
                "unique_together": {("building", "code")},
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_code",
                    models.CharField(help_text="Room code/identifier", max_length=100),
                ),
                (
                    "room_description",
                    models.TextField(
                        blank=True, help_text="Room description", null=True
                    ),
                ),
                (
                    "space_type",
                    models.CharField(
                        choices=[
                            ("room", "Room"),
                            ("office", "Office"),
                            ("meeting_room", "Meeting Room"),
                            ("corridor", "Corridor"),
                            ("laundry_room", "Laundry Room"),
                            ("toilet", "Toilet"),
                            ("balcony", "Balcony"),
                            ("front_yard", "Front Yard"),
                            ("garage", "Garage"),
                            ("container", "Container"),
                            ("mwa", "MWA"),
                            ("other", "Other"),
                        ],
                        help_text="Type of space",
                        max_length=50,
                    ),
                ),
                (
                    "building_code",
                    models.CharField(
                        help_text="Building code reference", max_length=20
                    ),
                ),
                (
                    "square_meters",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Square meters (m²)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_of_rooms",
                    models.IntegerField(
                        default=1,
                        help_text="Quantity of rooms",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "actual_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual Sqm (m2) for SLA calculations",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "frequency_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Frequency Per Day",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "frequency_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Frequency Per Week",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_frequency_per_month",
                    models.IntegerField(
                        help_text="Max Frequency Per Month",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "weekly_required_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total m² Week",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "monthly_cap_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="EoM Invoicing max. Sqm (m2)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("service_start_date", models.DateField(help_text="Start Date")),
                ("service_end_date", models.DateField(help_text="End Date")),
                (
                    "weeks_of_service",
                    models.IntegerField(
                        help_text="# Weeks of service",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "custom_field_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom field name (set by Admin/Manager)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "custom_field_value",
                    models.TextField(
                        blank=True, help_text="Custom field value", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="locations.building",
                    ),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="locations.camp",
                    ),
                ),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="locations.compound",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="locations.floor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["room_code"],
                "unique_together": {("floor", "room_code")},
            },
        ),
    ]
