# Generated by Django 4.2.23 on 2025-09-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="timezone",
            field=models.CharField(
                default="Europe/Belgrade",
                help_text="Camp timezone (e.g., 'Europe/Belgrade' for Kosovo/Prishtina)",
                max_length=50,
            ),
        ),
    ]
