# Generated by Django 4.2.23 on 2025-09-04 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="month_cutoff_day",
            field=models.IntegerField(
                default=31,
                help_text="Month cutoff day (0=End of Month, 1-31=specific day)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="timezone",
            field=models.CharField(
                default="Europe/Berlin", help_text="Camp timezone", max_length=50
            ),
        ),
    ]
