# Generated by Django 4.2.23 on 2025-09-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_update_camp_timezone_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="timezone",
            field=models.CharField(
                default="Europe/Berlin",
                help_text="Camp timezone (e.g., 'Europe/Berlin' for Kosovo/Prishtina)",
                max_length=50,
            ),
        ),
    ]
