# Generated by Django 4.2.24 on 2025-09-09 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_add_compound_urgent_sqm_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentCleaningRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title for the urgent cleaning request', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the cleaning requirements')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_sqm', models.DecimalField(decimal_places=2, help_text='SQM area that needs urgent cleaning', max_digits=10)),
                ('estimated_duration', models.IntegerField(help_text='Estimated duration in hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferred_start_time', models.DateTimeField(blank=True, help_text='Preferred start time for the cleaning', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_urgent_requests', to=settings.AUTH_USER_MODEL)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_requests', to='locations.compound')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Urgent Cleaning Request',
                'verbose_name_plural': 'Urgent Cleaning Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
