# Generated by Django 4.2.24 on 2026-07-03 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_urgentcleaningrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='space_type',
            field=models.CharField(choices=[('room', 'Room'), ('office', 'Office'), ('meeting_room', 'Meeting Room'), ('corridor', 'Corridor'), ('laundry_room', 'Laundry Room'), ('toilet', 'Toilet'), ('balcony', 'Balcony'), ('front_yard', 'Front Yard'), ('garage', 'Garage'), ('container', 'Container'), ('mwa', 'MWA'), ('dumpster', 'Dumpster (Garbage Collection)'), ('other', 'Other')], help_text='Type of space', max_length=50),
        ),
        migrations.CreateModel(
            name='MonthlyRollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(help_text='Start of the rollup period')),
                ('period_end', models.DateField(help_text='End of the rollup period')),
                ('required_weekly_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('achieved_weekly_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('achieved_monthly_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capped_monthly_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sla_weekly_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sla_monthly_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rollups', to='locations.building')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rollups', to='locations.camp')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rollups', to='locations.compound')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rollups', to='locations.room')),
            ],
            options={
                'verbose_name': 'Monthly Rollup',
                'verbose_name_plural': 'Monthly Rollups',
                'ordering': ['-period_start', 'room__room_code'],
                'unique_together': {('room', 'period_start', 'period_end')},
            },
        ),
    ]
