# Generated by Django 4.2.30 on 2026-07-07 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_room_space_type_monthlyrollup'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='geo_polygon',
            field=models.TextField(blank=True, help_text='Optional GeoJSON geometry outlining a public area (Polygon)', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map placement (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map placement (WGS84)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='space_type',
            field=models.CharField(choices=[('room', 'Room'), ('office', 'Office'), ('meeting_room', 'Meeting Room'), ('corridor', 'Corridor'), ('laundry_room', 'Laundry Room'), ('toilet', 'Toilet'), ('balcony', 'Balcony'), ('front_yard', 'Front Yard'), ('garage', 'Garage'), ('container', 'Container'), ('mwa', 'MWA'), ('dumpster', 'Dumpster (Garbage Collection)'), ('park', 'Park / Green Space'), ('city_center', 'City Center / Public Plaza'), ('school_yard', 'School Yard'), ('other', 'Other')], help_text='Type of space', max_length=50),
        ),
        migrations.CreateModel(
            name='CollectionClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(help_text='Anonymized client identifier shown on the map (no name)', max_length=50, unique=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('exempt', 'Exempt (public)')], default='unpaid', max_length=20)),
                ('paid_until', models.DateField(blank=True, help_text='Service paid through this date (optional)', null=True)),
                ('internal_note', models.TextField(blank=True, help_text='Internal only — never exposed on the public map', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(blank=True, help_text='Neighbourhood this client belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='locations.compound')),
            ],
            options={
                'verbose_name': 'Collection Client',
                'verbose_name_plural': 'Collection Clients',
                'ordering': ['client_code'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Billing client for this dumpster/collection point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dumpsters', to='locations.collectionclient'),
        ),
    ]
