# Generated by Django 4.2.30 on 2026-07-07 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_room_geo_polygon_room_latitude_room_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='geo_polyline',
            field=models.TextField(blank=True, help_text="GeoJSON MultiLineString of the street's road segments", null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='collection_weekday',
            field=models.IntegerField(blank=True, help_text='Scheduled collection weekday (0=Mon..6=Sun)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='room',
            name='last_collected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful collection', null=True),
        ),
    ]
