# Generated by Django 4.2.30 on 2026-07-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_building_geo_polyline_room_collection_weekday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'Street', 'verbose_name_plural': 'Streets'},
        ),
        migrations.AlterModelOptions(
            name='camp',
            options={'ordering': ['name'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='compound',
            options={'ordering': ['name'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['name'], 'verbose_name': 'Street Segment', 'verbose_name_plural': 'Street Segments'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_code'], 'verbose_name': 'Service Point', 'verbose_name_plural': 'Service Points'},
        ),
    ]
