# Generated by Django 4.2.30 on 2026-07-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_building_options_alter_camp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_tracking_enabled', models.BooleanField(default=True, help_text='When on, unpaid clients are flagged and skipped on the map. When off, everyone is collected and billed monthly.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operations Settings',
                'verbose_name_plural': 'Operations Settings',
            },
        ),
    ]
