# Generated by Django 4.2.30 on 2026-07-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_operationsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dumpster_type',
            field=models.CharField(blank=True, choices=[('household', 'Household (single family)'), ('communal', 'Communal (shared block)')], default='household', help_text='For dumpsters: single-family household bin or shared communal block bin', max_length=20),
        ),
    ]
