# Generated by Django 4.2.30 on 2026-07-07 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_room_dumpster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='center_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Map center latitude for this site (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='center_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Map center longitude for this site (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='default_zoom',
            field=models.IntegerField(default=13, help_text='Default map zoom level for this site', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='compound',
            name='geo_polygon',
            field=models.TextField(blank=True, help_text='GeoJSON Polygon of the zone boundary (drawn on the map)', null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='osm_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When streets were last populated from OSM', null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='osm_message',
            field=models.TextField(blank=True, help_text='Result/error message from the last OSM job', null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='osm_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='idle', help_text='Status of the last OpenStreetMap street-population job', max_length=20),
        ),
        migrations.AddField(
            model_name='compound',
            name='osm_street_count',
            field=models.IntegerField(default=0, help_text='Streets created on the last OSM population run'),
        ),
    ]
