# Generated by Django 4.2.30 on 2026-07-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_team_employee_count_team_equipment_team_vehicle_and_more'),
        ('locations', '0011_camp_center_lat_camp_center_lng_camp_default_zoom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='collection_shift',
            field=models.ForeignKey(blank=True, help_text='Collection shift / time window for this zone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='accounts.shift'),
        ),
        migrations.AddField(
            model_name='compound',
            name='collection_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Weekday this zone is collected (0=Mon..6=Sun). New dumpsters inherit this.', null=True),
        ),
    ]
