# Generated by Django 4.2.30 on 2026-07-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_compound_collection_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='collection_shift',
        ),
    ]
