# Generated by Django 4.2.30 on 2026-07-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_team_employee_count_team_equipment_team_vehicle_and_more'),
        ('locations', '0013_remove_compound_collection_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='assigned_team',
            field=models.ForeignKey(blank=True, help_text='Team responsible for collecting this zone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_zones', to='accounts.team'),
        ),
    ]
