# Generated by Django 4.2.30 on 2026-07-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_compound_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface area (m²) computed from the zone boundary', max_digits=12, null=True),
        ),
    ]
