# Generated by Django 4.2.30 on 2026-07-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_compound_area_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='zone_type',
            field=models.CharField(choices=[('collection', 'Collection zone (dumpsters)'), ('public_area', 'Public area (SQM)')], default='collection', help_text='Collection zone (dumpsters) or public area (SQM)', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='space_type',
            field=models.CharField(choices=[('room', 'Room'), ('office', 'Office'), ('meeting_room', 'Meeting Room'), ('corridor', 'Corridor'), ('laundry_room', 'Laundry Room'), ('toilet', 'Toilet'), ('balcony', 'Balcony'), ('front_yard', 'Front Yard'), ('garage', 'Garage'), ('container', 'Container'), ('mwa', 'MWA'), ('dumpster', 'Dumpster (Garbage Collection)'), ('public_area', 'Public Area (SQM)'), ('park', 'Park / Green Space'), ('city_center', 'City Center / Public Plaza'), ('school_yard', 'School Yard'), ('other', 'Other')], help_text='Type of space', max_length=50),
        ),
    ]
