# Generated by Django 4.2.23 on 2025-09-02 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCleaningTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Date for this cleaning task")),
                (
                    "index_in_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Task index for the day (1st, 2nd, 3rd cleaning of the day)",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("missed", "Missed"),
                            ("re_clean_required", "Re-clean Required"),
                        ],
                        default="planned",
                        help_text="Current state of the task",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_tasks",
                        to="locations.room",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned shift for this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Cleaning Task",
                "verbose_name_plural": "Daily Cleaning Tasks",
                "ordering": ["date", "shift__start_time", "index_in_day"],
            },
        ),
        migrations.CreateModel(
            name="ScanEventDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("barcode_scanned", models.CharField(max_length=200)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="locations.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["room", "user", "timestamp"],
                        name="scans_scane_room_id_7dafda_idx",
                    )
                ],
                "unique_together": {("room", "user", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("cleaned", "Cleaned"),
                            ("recleaned", "Re-cleaned"),
                            ("urgent_clean", "Urgent Clean"),
                        ],
                        help_text="Type of scan event",
                        max_length=20,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Device identifier used for scanning",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "barcode_scanned",
                    models.CharField(
                        help_text="Barcode data that was scanned", max_length=200
                    ),
                ),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False, help_text="Is this an urgent cleaning request"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated daily cleaning task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="scans.dailycleaningtask",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to="locations.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Event",
                "verbose_name_plural": "Scan Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["room", "timestamp"],
                        name="scans_scane_room_id_359c0b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="scans_scane_user_id_e2efd9_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="scans_scane_timesta_08bc3d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dailycleaningtask",
            index=models.Index(
                fields=["date", "state"], name="scans_daily_date_6fe1ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailycleaningtask",
            index=models.Index(
                fields=["assigned_to", "date"], name="scans_daily_assigne_adbf8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailycleaningtask",
            index=models.Index(
                fields=["room", "date"], name="scans_daily_room_id_6b93a6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailycleaningtask",
            unique_together={("room", "date", "index_in_day")},
        ),
    ]
