# Generated by Django 4.2.24 on 2026-07-03 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_team_team_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0005_alter_room_space_type_monthlyrollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('CLEANED', 'Cleaned'), ('RECLEANED', 'Recleaned'), ('URGENT_CLEAN', 'Urgent Clean')], default='CLEANED', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode_scanned', models.CharField(blank=True, max_length=200, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='accounts.dailycleaningtask')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='locations.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['room', 'timestamp'], name='scans_scane_room_id_359c0b_idx')],
            },
        ),
    ]
